### ISSUE TITLE
Journal version training dataset?

### ISSUE THREAD

**Issue by laisimiao** [QiaoLiuHit/LSOTB-TIR#12]
I see that there are 136 seqs in evaluation dataset of journal version, which is 25 larger than 100 short-term + 11 long-term. Therefore, does it mean these25 seqs plus original 1280 training seqs of conference version form the 1305 training seqs that match the journal paper description?

**Comment by QiaoLiuHit** [comment]
Yes, that right.  We move these simple tracking sequences to the training dataset.
