### ISSUE TITLE
XML issues

### ISSUE THREAD

**Issue by image000** [QiaoLiuHit/LSOTB-TIR#13]
作者好，发现数据集中TIR_training_001 的person_041：00000031.xml，Airplane_002 : 00000088.xml中的 <filename>有错误。可以修改

**Comment by QiaoLiuHit** [comment]
> 作者好，发现数据集中TIR_training_001 的person_041：00000031.xml，Airplane_002 : 00000088.xml中的 有错误。可以修改

Thanks.

**Comment by chenzhy223** [comment]
什么错误呢
