### ISSUE TITLE
hi, can you provide a Baidu disk download link of all your datasets？

### ISSUE THREAD

**Issue by ZealerMUFC** [QiaoLiuHit/LSOTB-TIR#2]
hi，the links of all your dataset provided in Mega is not easy to download based on my internet situation. So if you can provide a baidudisk link, I will  appreciate your help very much.

**Comment by QiaoLiuHit** [comment]
@ZealerMUFC  Now you can download the dataset from [baidu disk]( https://pan.baidu.com/s/18VQ6Fz-QUYEEyQOcj9Ja3w )
code：dr3i

**Comment by ZealerMUFC** [comment]
Thank you very much.
