### ISSUE TITLE
cat_D_001 or car_D_001 in the test sequences?

### ISSUE THREAD

**Issue by ZhouZhang233** [QiaoLiuHit/LSOTB-TIR#4]
When I evaluate my tracker on LSOTB-TIR test dataset. I get an error that lacks "cat_D_001_myTracker.mat". 
So I check the test sequences.  I found out it is not "cat_D_001", but “car_D_001” in the test sequences.
Could you please check it out?
Thanks!

**Comment by QiaoLiuHit** [comment]
Thanks a lot. We provided a wrong sequence. It should be 'cat_D_001' instead of 'car_D_001'. We have updated the evaluate dataset in [baidu pan](https://pan.baidu.com/s/18VQ6Fz-QUYEEyQOcj9Ja3w#list/path=%2F), code:dr3i.
