### ISSUE TITLE
drawResultBB 中报错问题

### ISSUE THREAD

**Issue by dudiaoxifenglie** [QiaoLiuHit/LSOTB-TIR#5]
您好，
MATLAB2020a
对所有跟踪算法在序列中的跟踪效果进行绘制，但提示如下（line 差异在于自己在代码中添加了注释）：

错误使用 legend (line 278)
元素 4 不是字符串标量或字符数组。元胞输入的所有元素都必须为字符串标量或字符数组。

出错 drawResultBB (line 128)
        legend(legends_handle, legends_desc);% tracker legend

**Comment by QiaoLiuHit** [comment]
> 您好，
> MATLAB2020a
> 对所有跟踪算法在序列中的跟踪效果进行绘制，但提示如下（line 差异在于自己在代码中添加了注释）：
> 
> 错误使用 legend (line 278)
> 元素 4 不是字符串标量或字符数组。元胞输入的所有元素都必须为字符串标量或字符数组。
> 
> 出错 drawResultBB (line 128)
> legend(legends_handle, legends_desc);% tracker legend

我用的Matlab2017a, 没有错误。Matlab2020a 应该也可以用，我猜想可能是你的’configTrackers.m‘文件中的tracker配置的问题，或是tracker生成了结果文件mat有问题，请仔细检查。
