### ISSUE TITLE
关于12类挑战的问题

### ISSUE THREAD

**Issue by 1071189147** [QiaoLiuHit/LSOTB-TIR#7]
请问每一类挑战分别对应哪些序列？
可以公开您在做子集评估时每一类挑战的序列信息吗？

**Comment by QiaoLiuHit** [comment]
> 请问每一类挑战分别对应哪些序列？ 可以公开您在做子集评估时每一类挑战的序列信息吗？

You can find the attribute annotations in 'anno/att' folder. The corresponding attritube name in the 'run_evaluation.m-->att_name'.
